language: python
env:
    - TEST=python2.7
    - TEST=python2.6
    - TEST=python2.5
    - TEST=nopygments
    - TEST=nonose
    - TEST=jython JAR=http://downloads.sourceforge.net/project/jython/jython/2.5.2/jython_installer-2.5.2.jar
before_install:
  - if [[ $TEST == jython ]]; then curl -O $JAR && java -jar $(basename $JAR) -sd ~/jython && export PATH=~/jython:$PATH; fi
script: make $TEST
