language: python
env:
    - TEST=python2.7
    - TEST=python2.6
    - TEST=python2.5
    - TEST=nopygments
    - TEST=nonose
    - TEST=jython
    - JYTHON_URL=http://downloads.sourceforge.net/project/jython/jython/2.5.2/jython_installer-2.5.2.jar
before_install:
  - if [[ $TEST == jython ]]; then wget $JYTHON_URL && java -jar jython_installer-2.5.2.jar -sd ~/jython && export PATH=~/jython:$PATH; fi
script: make $TEST
